### ISSUE TITLE
Issues when running from within source directory

### ISSUE THREAD

**Issue by jotelha** [IMTEK-Simulation/dtool-lookup-gui#14]
In the case of standard install `pip install .`  and run from within the source directory

```
(jlh-imtek-python-3.8) jotelha@jotelha-asus-ubuntu-20-04:~/git/dtool/dtool-lookup-gui$ python -m dtool_lookup_gui
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/jotelha/git/dtool/dtool-lookup-gui/dtool_lookup_gui/__main__.py", line 27, in <module>
    run_gui()
  File "/home/jotelha/git/dtool/dtool-lookup-gui/dtool_lookup_gui/MainApplication.py", line 448, in run_gui
    settings = Settings()
  File "/home/jotelha/git/dtool/dtool-lookup-gui/dtool_lookup_gui/MainApplication.py", line 163, in __init__
    schema_source = Gio.SettingsSchemaSource.new_from_directory(
gi.repository.GLib.Error: g-file-error-quark: Failed to open file “/home/jotelha/git/dtool/dtool-lookup-gui/dtool_lookup_gui/gschemas.compiled”: open() failed: No such file or directory (4)
```
 or if installed with `pip install -e .`  for testing and run from anywhere
````
$ python -m dtool_lookup_gui
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/jotelha/git/dtool/dtool-lookup-gui/dtool_lookup_gui/__main__.py", line 27, in <module>
    run_gui()
  File "/home/jotelha/git/dtool/dtool-lookup-gui/dtool_lookup_gui/MainApplication.py", line 448, in run_gui
    settings = Settings()
  File "/home/jotelha/git/dtool/dtool-lookup-gui/dtool_lookup_gui/MainApplication.py", line 163, in __init__
    schema_source = Gio.SettingsSchemaSource.new_from_directory(
gi.repository.GLib.Error: g-file-error-quark: Failed to open file “/home/jotelha/git/dtool/dtool-lookup-gui/dtool_lookup_gui/gschemas.compiled”: open() failed: No such file or directory (4)
```

**Comment by jotelha** [comment]
Explained in https://github.com/IMTEK-Simulation/dtool-lookup-gui/pull/28/commits/f813725e6e2035aec23e9811784b0de08f905b0a
