### ISSUE TITLE
Listing base_uris via API fails for users without admin privileges

### ISSUE THREAD

**Issue by jotelha** [IMTEK-Simulation/dtool-lookup-gui#31]
The lookup api call [`list_base_uri`](https://github.com/IMTEK-Simulation/dtool-lookup-api/blob/3047bae531b64f6af8da9a11936f083885eee742/dtool_lookup_api/core/LookupClient.py#L182-L184) uses route `/admin/base_uri/list`, hence fails for any user w/o admin privileges on the server. What might be easily doable for a "normal" user is a query for all base URIs themselves are allowed access to. Will open according issue on lookup api.

```
ERROR:asyncio:Task exception was never retrieved
future: <Task finished name='Task-12' coro=<SignalHandler._refresh_list_of_endpoints() done, defined at /home/jotelha/git/dtool/dtool-lookup-gui/dtool_lookup_gui/SettingsDialog.py:81> exception=ContentTypeError(RequestInfo(url=URL('https://simdata.vm.uni-freiburg.de:5000/admin/base_uri/list'), method='GET', headers=<CIMultiDictProxy('Host': 'simdata.vm.uni-freiburg.de:5000', 'Authorization': 'Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTYzNzQxODY3OCwianRpIjoiYzg4NjUxNWYtMmMzYi00OWU2LWIxMjMtMmQzMGQ0ZWUzYzc4IiwidHlwZSI6ImFjY2VzcyIsInN1YiI6ImpoMTEzMCIsIm5iZiI6MTYzNzQxODY3OCwiZXhwIjoxNjM3NzQyNjc4fQ.Z_F9HGzJRcFqvqqA_-6Fp64bIJVOIGHi4XFk1Rjtz62qz-e0HnkdBDdBz6BI6hKcUAFg9StqkHBt8slkDeuIhSGbUkrHw-m3JchGQ5W2F_MOa1ZBvLYJo4oQF7SQt6JjkY4k-kVCAjxH11vtqsVLcwk2JryMYl9CnvbES44wzhbSh-Rsw6sBYTe2-QNTmG2DnIY2Iw0NGPfPTninj0LMsto6Y44gR4J0G7ZKMT9-fuY1UlNOrVgT6XzQwoXY28XpRwns-2sWFF-6AlO1jJ0pkDP8f-M2Y2aVQrBu05M5rrIO4wn0VpT8CVYQ7vjs0hCf9PLeSh68K2Cr0DLZ1WCDSg', 'Accept': '*/*', 'Accept-Encoding': 'gzip, deflate', 'User-Agent': 'Python/3.8 aiohttp/3.7.3')>, real_url=URL('https://simdata.vm.uni-freiburg.de:5000/admin/base_uri/list')), (), message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8', headers=<CIMultiDictProxy('Server': 'gunicorn', 'Date': 'Sat, 20 Nov 2021 14:36:03 GMT', 'Connection': 'close', 'Content-Type': 'text/html; charset=utf-8', 'Content-Length': '232', 'Access-Control-Allow-Origin': '*')>)>
Traceback (most recent call last):
  File "/home/jotelha/git/dtool/dtool-lookup-gui/dtool_lookup_gui/SettingsDialog.py", line 85, in _refresh_list_of_endpoints
    base_uris = await self.main_application.lookup_tab.lookup.list_base_uris()
  File "/home/jotelha/venv/jlh-imtek-python-3.8/lib/python3.8/site-packages/dtool_lookup_api/core/LookupClient.py", line 184, in list_base_uris
    return await self._get('/admin/base_uri/list')
  File "/home/jotelha/venv/jlh-imtek-python-3.8/lib/python3.8/site-packages/dtool_lookup_api/core/LookupClient.py", line 99, in _get
    return await r.json()
  File "/home/jotelha/venv/jlh-imtek-python-3.8/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 1097, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8', url=URL('https://simdata.vm.uni-freiburg.de:5000/admin/base_uri/list')
```

![image](https://user-images.githubusercontent.com/1868344/142730318-31111c60-d320-44a8-bab1-8060dfe34757.png)

I might just hide the empty storage settings for now and ignore the exception.

**Comment by pastewka** [comment]
This needs to be implemented in `dtool-lookuo-server`, not `dtool-lookup-api`, correct?

**Comment by jotelha** [comment]
Actually, looking at the lookup server, I think it can be done just with the `/user/info` route and the answer's `search_permissions_on_base_uris` and `register_permissions_on_base_uris` fields, see  https://github.com/jic-dtool/dtool-lookup-server#getting-information-about-ones-own-permissions
 and the tests at
https://github.com/jic-dtool/dtool-lookup-server/blob/12baba73eebc668b4998ae2c2ea43946dc3bf856/tests/test_user_routes.py#L32-L47

**Comment by jotelha** [comment]
Addressed by https://github.com/IMTEK-Simulation/dtool-lookup-gui/pull/40. The /user/info route, however, needs the username, hence won't work if only the token is cached in the dtool config.
