### ISSUE TITLE
Windows 10: ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine

### ISSUE THREAD

**Issue by jotelha** [IMTEK-Simulation/dtool-lookup-gui#62]
GUI 0.4.0 loads dataset lists, but throws
```
ERROR:asyncio:Fatal read error on pipe transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x000002a1cffa3b20>
transport: <gbulb.transports.SocketTransport object at 0x000002a1d2557280>
Traceback (most recent call last):
  File "C:/msys64/home/JohannesH▒rmann/venv/python-3.9/lib/python3.9/site-packages/gbulb/transports.py", line 146, in _loop_reading
    data = fut.result()  # Deliver data later in "finally" clause
  File "C:/msys64/home/JohannesH▒rmann/venv/python-3.9/lib/python3.9/site-packages/gbulb/glib_events.py", line 572, in handle_ready
    (done, result) = callback(*args)
  File "C:/msys64/home/JohannesH▒rmann/venv/python-3.9/lib/python3.9/site-packages/gbulb/glib_events.py", line 685, in channel_readable
    return (True, read_func(channel, nbytes))
  File "C:/msys64/home/JohannesH▒rmann/venv/python-3.9/lib/python3.9/site-packages/gbulb/glib_events.py", line 646, in read_func
    return sock.recv(nbytes, flags)
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine
```

Also, GUI sometimes freezes throwing the same exception repeatedly when selecting a dataset on the lookup server and loading its README. 

## Environment: 

MSYS2 MinGW 64-bit (`msys2-x86_64-20210725.exe`)

Setup:

```
# system packages (might be incomplete)
pacman -S mingw-w64-x86_64-cython
pacman -S mingw-w64-x86_64-python-aiohttp
pacman -S mingw-w64-x86_64-python-asgiref
pacman -S mingw-w64-x86_64-python-boto3 # required
pacman -S mingw-w64-x86_64-python-cairo
pacman -S mingw-w64-x86_64-python-click
pacman -S mingw-w64-x86_64-python-jsonschema  # required
pacman -S mingw-w64-x86_64-python-numpy # required
pacman -S mingw-w64-x86_64-python-pip-tools
pacman -S mingw-w64-x86_64-python-requests
pacman -S mingw-w64-x86_64-python-ruamel-yaml
pacman -S mingw-w64-x86_64-python-ruamel.yaml.clib
pacman -S mingw-w64-x86_64-python-scipy # required
pacman -S mingw-w64-x86_64-python-setuptools
pacman -S mingw-w64-x86_64-python-setuptools-scm
pacman -S mingw-w64-x86_64-python-urllib3
pacman -S mingw-w64-x86_64-python-yaml # required

# pip
curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
python get-pip.py
# (ignore any error from previous step)
python -m pip install -U --force-reinstall pip

# venv
 python -m venv ~/venv/python-3.9 --system-site-packages

# install dtool-lookup-gui and dependencies 

# exhaustive environent documentation
pacman -Q > mingw64_pacman_Q.txt
pip freeze > mingw64_pip_freeze.txt
source ~/venv/python-3.9/bin/activate # venv with --system-site-packages
pip freeze > mingw64_venv_pip_freeze.txt
pip freeze --local > mingw64_venv_pip_freeze_local.txt
```

Content of  `mingw64_venv_pip_freeze_local.txt`
```
cffi==1.15.0
click-plugins==1.1.1
cryptography==3.3.2
dtool-cli==0.7.1
dtool-config==0.4.1
dtool-create==0.23.4
dtool-http==0.5.1
dtool-info==0.16.2
dtool-lookup-api==0.5.0
# Editable install with no version control (dtool-lookup-gui==0.4.0)
-e c:/msys64/home/johannesh▒rmann/venv/python-3.9/lib/python3.9/site-packages
dtool-s3==0.12.0
dtool-smb==0.1.0
dtool-symlink==0.3.1
dtoolcore==3.18.1
gbulb==0.6.2
Jinja2==3.0.3
jwt==1.3.1
MarkupSafe==2.0.1
pyasn1==0.4.8
pycparser==2.21
Pygments==2.10.0
pysmb==1.2.7
PyYAML==6.0
```

**Comment by jotelha** [comment]
Superficially addressed by https://github.com/IMTEK-Simulation/dtool-lookup-gui/pull/71/commits/708b21577350534fa55d4f6b1d1791a7b9c5c543, filter related exceptions from log messageas displayed in GUI error bar.
