### ISSUE TITLE
Windows: Issues with non-ASCII characters in path names

### ISSUE THREAD

**Issue by jotelha** [IMTEK-Simulation/dtool-lookup-gui#70]
Local folders like .../JohannesHörmann/... can be added and appear in the endpoint list, but characters are not displayed correctly and path is actually not found on windows,

```
Traceback (most recent call last):
  File "C:/msys64/mingw64/lib/python3.9/concurrent/futures/process.py", line 243, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "C:/msys64\home\JohannesH▒rmann\git\dtool-lookup-gui/dtool_lookup_gui/models/datasets.py", line 152, in _list_proto_datasets
    for dataset in dtoolcore.iter_proto_datasets_in_base_uri(base_uri):
  File "C:/msys64/mingw64/lib/python3.9/site-packages/dtoolcore/__init__.py", line 336, in _iter_datasets_in_base_uri
    for uri in StorageBroker.list_dataset_uris(base_uri, config_path):
  File "C:/msys64/mingw64/lib/python3.9/site-packages/dtoolcore/storagebroker.py", line 468, in list_dataset_uris
    for d in os.listdir(path):
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\Users\\JohannesH%C3%B6rmann\\datasets'
````

**Comment by jotelha** [comment]
Solved by https://github.com/IMTEK-Simulation/dtool-lookup-gui/pull/71
