### ISSUE TITLE
Division by zero when copying empty dataset

### ISSUE THREAD

**Issue by jotelha** [IMTEK-Simulation/dtool-lookup-gui#72]
```
[2022-02-03 00:50:33,581 - show_error - main_window.py:684] ERROR: Traceback (most recent call last):
  File "c:/msys64/home/johannesh▒rmann/git/dtool-lookup-gui/dtool_lookup_gui/views/main_window.py", line 571, in _copy
    await self._copy_manager.copy(self.dataset_list_box.get_selected_row().dataset, widget.destination)
  File "c:/msys64/home/johannesh▒rmann/git/dtool-lookup-gui/dtool_lookup_gui/utils/copy_manager.py", line 40, in copy
    await dataset.copy(destination, progressbar=tracker)
  File "c:/msys64/home/johannesh▒rmann/git/dtool-lookup-gui/dtool_lookup_gui/models/datasets.py", line 309, in copy
    await _copy_dataset(self.uri, target_base_uri, resume, auto_resume, progressbar)
  File "c:/msys64/home/johannesh▒rmann/git/dtool-lookup-gui/dtool_lookup_gui/models/datasets.py", line 209, in _copy_dataset
    with ProgressBar(length=num_items,
  File "c:/msys64/home/johannesh▒rmann/git/dtool-lookup-gui/dtool_lookup_gui/utils/progressbar.py", line 57, in __enter__
    self._pb.set_step(0, self._length)
  File "c:/msys64/home/johannesh▒rmann/git/dtool-lookup-gui/dtool_lookup_gui/widgets/progress_popover_menu.py", line 60, in set_step
    self._progress_bar.set_fraction(self.fraction)
  File "c:/msys64/home/johannesh▒rmann/git/dtool-lookup-gui/dtool_lookup_gui/widgets/progress_popover_menu.py", line 76, in fraction
    return self._step / self._length
ZeroDivisionError: division by zero
```

**Comment by jotelha** [comment]
Solved by https://github.com/IMTEK-Simulation/dtool-lookup-gui/pull/71
